# ==============================================================================
# ANNOTATED SOURCE: ast.nim — M/MUMPS Abstract Syntax Tree Definitions
# ==============================================================================
#
# This file defines the complete AST (Abstract Syntax Tree) for M/MUMPS.
# Every M program, once parsed, is represented as a tree of these nodes.
# The AST is the bridge between the parser (which builds it) and the
# runtime (which executes it).
#
# M/MUMPS Language Overview (for context):
#   M is a line-oriented language. Each line can have:
#     - An optional label (entry point name)
#     - Zero or more commands, each with optional postconditionals
#     - Commands are separated by whitespace (not semicolons)
#   M has no block structure in the traditional sense — IF and FOR
#   scope to the rest of the line (or the indented block that follows).
#
# ANSI/MDC X11.1-1995 Standard References:
#   Section 6: Variables — local, global, special, subscripted
#   Section 7: Operators — arithmetic, string, comparison, logical, pattern
#   Section 8: Special Variables — $HOROLOG, $IO, $TEST, etc.
#   Section 9: Intrinsic Functions — $ASCII, $CHAR, $DATA, etc.
#   Section 10: Commands — SET, WRITE, IF, FOR, QUIT, KILL, NEW, DO, etc.
#
# Design Decisions:
#   - Variant objects (case objects) are used for AST nodes. This gives
#     us tagged unions with compile-time exhaustive matching — the Nim
#     compiler will catch missing cases in the runtime.
#   - Expressions and commands are separate hierarchies because they have
#     fundamentally different evaluation semantics (expressions return
#     values; commands have side effects).
#   - Pattern atoms are embedded in the expression tree as ePattern nodes
#     because the ? operator is an infix binary operator in M.
#   - Postconditionals are attached to CommandNode, not to individual
#     command types, because ALL M commands can have postconditionals.
#
# Genera-Style Introspection Notes:
#   - A Genera M system would present the AST as a browsable tree
#   - Each node would have source location info (not yet implemented)
#   - The Stefi inspector would show node type, children, and attributes
#   - Static analysis passes would annotate the tree with type info,
#     reachability, variable usage, etc.
#   - A compiler could transform the AST for optimization (constant
#     folding, dead code elimination, etc.)
#
# Cross-References:
#   - Generated by: parser.nim (parseExpr, parseLine, parseCommand, etc.)
#   - Consumed by: runtime.nim (eval, runLine, execSet, execFor, etc.)
#   - Pattern atoms use: pattern.nim (matchPattern, matchesCode)
#
# ==============================================================================

type
  ## BinOp — Binary Operators in M
  ##
  ## ANSI/ISO Section 7: M has the following binary operators:
  ##
  ## Arithmetic (Section 7.1):
  ##   +  Addition
  ##   -  Subtraction
  ##   *  Multiplication
  ##   /  Division
  ##   \  Integer division (RSM extension, not in ANSI standard)
  ##   #  Modulus
  ##   ** Exponentiation
  ##
  ## String (Section 7.2):
  ##   _  Concatenation (underscore, not dot — this surprises many people)
  ##
  ## Comparison (Section 7.3):
  ##   =  Equals (numeric if both canonical, else string)
  ##   '= Not equals
  ##   <  Less than
  ##   >  Greater than
  ##   '< Not less than (i.e., >=)
  ##   '> Not greater than (i.e., <=)
  ##   ]  Follows (string comparison: "B"]"A" is true)
  ##   '] Does not follow
  ##   [  Contains ("ABC"["B" is true)
  ##   '[ Does not contain
  ##
  ## Logical (Section 7.4):
  ##   &  AND
  ##   !  OR (! is OR, not | — historical)
  ##
  ## Pattern (Section 7.5):
  ##   ?  Pattern match (right operand is a pattern, not a regular expr)
  ##   '? Not pattern match
  ##
  ## Design Decision: bSortAfter is defined but not used in the parser
  ## — it's reserved for potential future use. The standard's "sorts after"
  ## concept is distinct from "follows" but rarely used.
  BinOp* = enum
    bAdd, bSub, bMul, bDiv, bIntDiv, bMod, bPow, bConcat,
    bEql, bNeql, bLt, bGt, bNlt, bNgt, bFollows, bSortAfter,
    bContains, bNotFollows, bNotContains, bAnd, bOr

  ## PatternAtom — One Element in a Pattern Match
  ##
  ## ANSI/ISO Section 7.5: A pattern consists of one or more pattern
  ## atoms. Each atom has:
  ##   count:  Minimum number of characters to match (default 1)
  ##   code:   The character class code (A, N, E, U, L, P, C, H)
  ##   orMore: If true, matches count-or-more (the "." in "3.A")
  ##
  ## Example: "2.4N" → PatternAtom(count=2, code='N', orMore=true)
  ##          The parser also stores the upper bound (4) but the runtime
  ##          only needs the minimum and the orMore flag.
  ##
  ## Genera Note: A pattern inspector would display atoms as a structured
  ## list with their match results against test strings.
  PatternAtom* = object
    count*: int
    code*: char
    orMore*: bool

  ## ExprKind — Expression Node Types
  ##
  ## M expressions (Section 7) can be:
  ##   numLit:   Numeric literal (e.g., 42, 3.14)
  ##   eStr:     String literal (e.g., "hello")
  ##   eVar:     Variable reference (local, global, or subscripted)
  ##   eFunc:    Intrinsic function call (e.g., $PIECE(x,"^",2))
  ##   eSvar:    Special variable (e.g., $HOROLOG, $IO, $TEST)
  ##   eNeg:     Unary negation (-x)
  ##   eNot:     Logical NOT ('x)
  ##   eBinary:  Binary operation (x + y, x = y, etc.)
  ##   ePattern: Pattern match (x ? 3U)
  ##
  ## Design Decision: We distinguish eFunc (function with args) from
  ## eSvar (special variable, no args) because they have different
  ## evaluation semantics. $HOROLOG is a special variable (always
  ## available, no arguments), while $PIECE is a function (requires
  ## arguments). Some M implementations blur this distinction.
  ##
  ## Genera Note: Each expression node would carry source location
  ## info for error reporting and debugging. A type inference pass
  ## could annotate nodes with [NUM], [STR], or [ANY].
  ExprKind* = enum
    numLit, eStr, eVar, eFunc, eSvar, eNeg, eNot, eBinary, ePattern

  ## Expr — Expression AST Node
  ##
  ## This is a variant object (tagged union). The `kind` field
  ## determines which fields are valid.
  ##
  ## For eVar (variable references):
  ##   vname: The variable name. Leading "^" indicates a global.
  ##          Examples: "X", "^GLOBAL", "%SYS"
  ##   subs:  Subscript expressions. A(1,2) has subs = [numLit(1), numLit(2)]
  ##
  ## For eFunc (intrinsic functions):
  ##   fname: Function name (uppercase, without $): "PIECE", "DATA", etc.
  ##   fargs: Argument expressions
  ##
  ## For ePattern (pattern match):
  ##   patLhs: The left operand (the string to match)
  ##   atoms:  The pattern atoms (from the right operand of ?)
  ##
  ## Genera Note: The inspector would display each node as a structured
  ## object with expandable children. For eBinary, it would show the
  ## operator, left subtree, and right subtree as a tree visualization.
  Expr* = ref object
    case kind*: ExprKind
    of numLit, eStr:
      sval*: string
    of eVar:
      ## Variable reference: name (with leading '^' for globals) + subscript exprs.
      vname*: string
      subs*: seq[Expr]
    of eFunc:
      ## Intrinsic function: name + args.
      fname*: string
      fargs*: seq[Expr]
    of eSvar:
      ## Special variable: name (e.g. "HOROLOG", "IO").
      sname*: string
    of eNeg, eNot:
      operand*: Expr
    of eBinary:
      op*: BinOp
      left*, right*: Expr
    of ePattern:
      patLhs*: Expr
      atoms*: seq[PatternAtom]

  ## SetKind — SET Target Variants
  ##
  ## ANSI/ISO Section 10.1: SET can assign to:
  ##   stVar:     Plain variable (e.g., SET X=5)
  ##   stPiece:   $PIECE target (e.g., SET $PIECE(A,"^",2)="B")
  ##   stExtract: $EXTRACT target (e.g., SET $EXTRACT(A,2,3)="XY")
  ##
  ## SET $PIECE and SET $EXTRACT are "write-back" operations — they
  ## modify part of an existing string. This is a distinctive M feature
  ## with no equivalent in most languages.
  ##
  ## Design Decision: We keep the target variable name separate from
  ## the $PIECE/$EXTRACT arguments because the variable is the LHS
  ## of the assignment, while the args specify which piece/position.
  SetKind* = enum
    stVar, stPiece, stExtract

  ## SetTarget — A SET Assignment Target
  ##
  ## For stVar:
  ##   tname: Variable name (^ prefix for globals)
  ##   tsubs: Subscript expressions
  ##
  ## For stPiece:
  ##   targetVar: The variable being modified
  ##   targs:     [delim, start, (end)] — the $PIECE arguments
  ##
  ## For stExtract:
  ##   targetVar: The variable being modified
  ##   targs:     [start, (end)] — the $EXTRACT arguments
  ##
  ## Genera Note: A SET $PIECE trace would show the original value,
  ## the piece being replaced, and the resulting value.
  SetTarget* = ref object
    case kind*: SetKind
    of stVar:
      ## Plain variable: name (^ prefix for global) + subscripts.
      tname*: string
      tsubs*: seq[Expr]
    of stPiece, stExtract:
      ## SET $PIECE(var, delim, start[, end]) = value / SET $EXTRACT(var, ...) = value
      targetVar*: string
      targs*: seq[Expr]

  ## SetItem — One SET Assignment
  ##
  ## M allows multiple assignments in one SET: SET A=1,B=2,C=3
  ## Each assignment is a SetItem with a target and a value expression.
  ## They are evaluated left to right.
  SetItem* = object
    target*: SetTarget
    value*: Expr

  ## WriteKind — WRITE Command Argument Types
  ##
  ## ANSI/ISO Section 10.26: WRITE can output:
  ##   wrExpr:     An expression (evaluated and printed)
  ##   wrNewline:  ! — outputs a newline character
  ##   wrFormFeed: # — outputs a form feed character
  ##   wrColumn:   ?n — moves to column n (tab stop)
  ##
  ## Design Decision: Format controls are separate from expressions
  ## because they have no value — they're side-effect-only operations.
  ## In the AST, wrExpr wraps the expression to write, while the
  ## format controls are simple markers.
  ##
  ## Genera Note: A WRITE trace would show each argument being output,
  ## with format controls shown as special markers: [NL], [FF], [TAB:5]
  WriteKind* = enum
    wrExpr, wrNewline, wrFormFeed, wrColumn

  ## WriteArg — One Argument to the WRITE Command
  WriteArg* = ref object
    case kind*: WriteKind
    of wrExpr:
      wexpr*: Expr
    of wrNewline, wrFormFeed:
      discard
    of wrColumn:
      col*: int

  ## ForSpec — FOR Loop Specification
  ##
  ## ANSI/ISO Section 10.4: FOR has several forms:
  ##   FOR var=init:step:limit  (counted FOR)
  ##   FOR var=init:step        (infinite FOR with step)
  ##   FOR var=init              (infinite FOR, step defaults to 1)
  ##   FOR                       (argumentless FOR — loops until QUIT)
  ##
  ## For the argumentless FOR, varName is "" and all exprs are nil.
  ##
  ## M's FOR is unique among languages:
  ##   - The loop variable is implicitly updated AFTER each iteration
  ##   - The limit is checked BEFORE each iteration
  ##   - If step is 0 and var != limit, the loop body executes once
  ##   - The loop can be exited with QUIT (which is the only way for
  ##     argumentless FOR)
  ##
  ## Design Decision: We store the FOR spec as a flat struct with
  ## optional expressions. This mirrors the M syntax directly.
  ##
  ## Genera Note: A FOR trace would show: var=init, step, limit,
  ## and for each iteration: current value, continue/exit decision.
  ForSpec* = object
    varName*: string
    initE*: Expr
    stepE*: Expr
    limitE*: Expr

  ## CommandNode — A Command with Its Postconditional
  ##
  ## ANSI/ISO Section 10: EVERY M command can have an optional
  ## postconditional: COMMAND:condition rest-of-args
  ##
  ## The postconditional is evaluated AFTER the command name is
  ## recognized but BEFORE the command arguments are processed.
  ## If the postconditional is false, the command is skipped.
  ##
  ## This is represented as a wrapper around Cmd because:
  ##   - It applies uniformly to all commands
  ##   - It separates the concern of "which command" from "when to execute"
  ##
  ## Design Decision: postcond is nil when there's no postconditional.
  ## This is more efficient than a special "always true" expression.
  ##
  ## Genera Note: A command trace would show: [IF:condition=1] SET X=5
  ## or [IF:condition=0] WRITE "skipped"
  CommandNode* = ref object
    postcond*: Expr
    cmd*: Cmd

  ## Line — A Sequence of Commands
  ##
  ## In M, a line is the fundamental unit of code. Commands on a line
  ## are separated by whitespace. They execute left to right.
  ##
  ## Design Decision: A Line is simply a sequence of CommandNodes.
  ## The parser handles the line-oriented nature of M by stopping
  ## at EOF or when it encounters a label.
  Line* = ref object
    cmds*: seq[CommandNode]

  ## CmdKind — Command Types
  ##
  ## ANSI/ISO Section 10: M commands. We include both standard and
  ## common extension commands.
  ##
  ## Standard Commands (ANSI/ISO):
  ##   cSet:    SET — assign values to variables
  ##   cWrite:  WRITE — output to current device
  ##   cIf:     IF — conditional execution (rest of line)
  ##   cFor:    FOR — loop construct
  ##   cQuit:   QUIT — exit loop or return from DO/extrinsic
  ##   cKill:   KILL — destroy variables
  ##   cKillExcept: KILL (A,B) — kill everything except listed vars
  ##   cNew:    NEW — save and shadow local variables
  ##   cHang:   HANG — suspend execution for N seconds
  ##   cLock:   LOCK — acquire resource locks
  ##   cMerge:  MERGE — copy entire variable trees
  ##   cXecute: XECUTE — execute string as M code
  ##   cDo:     DO — call a subroutine
  ##   cGoto:   GOTO — transfer control
  ##   cBreak:  BREAK — enter debugger (implementation-defined)
  ##   cRead:   READ — input from current device
  ##
  ## Extension Commands (RSM/common):
  ##   cZwrite: ZWRITE — display variables with structure
  ##   cZkill:  ZKILL — kill value but keep descendants
  ##   cNoop:   Placeholder for unimplemented commands
  ##
  ## Device Commands:
  ##   cOpen:   OPEN — open a device
  ##   cUse:    USE — select current device
  ##   cClose:  CLOSE — close a device
  ##
  ## Design Decision: cKillExcept is a separate kind from cKill because
  ## KILL (A,B) has fundamentally different semantics — it keeps listed
  ## variables instead of killing them. The parser determines which form.
  ##
  ## Genera Note: Each command would be inspectable with its arguments,
  ## postconditional, and execution status (executed/skipped/failed).
  CmdKind* = enum
    cSet, cWrite, cIf, cElse, cFor, cQuit, cKill, cKillExcept, cNew,
    cHang, cLock, cMerge, cXecute, cDo, cDoInline, cGoto, cBreak, cNoop,
    cZwrite, cZkill, cOpen, cUse, cClose, cRead,
    cZhalt, cZmessage, cZsave, cZsystem, cZtrap, cZbreak, cZgoto, cZprint, cZquit,
    cZload, cZstep, cZcontinue, cZremove

  ## Cmd — Command AST Node (without postconditional)
  ##
  ## Each variant carries the command-specific data:
  ##   cSet:      setItems — list of variable=value assignments
  ##   cWrite:    writeArgs — expressions and format controls
  ##   cIf:       ifCond + ifBody (the body is a Line — nested commands)
  ##   cFor:      forSpec + forBody
  ##   cQuit:     quitVal (optional return value)
  ##   cKill:     killRefs — variables to kill
  ##   cKillExcept: killKeep — variables to keep
  ##   cNew:      newNames — variable names to shadow
  ##   cHang:     hangExpr — seconds to wait
  ##   cLock:     lockRefs — resources to lock
  ##   cMerge:    mergePairs — (dst, src) pairs
  ##   cXecute:   xecExpr — string to execute as M code
  ##   cDo:       doArgs — label references (as expressions)
  ##   cGoto:     gotoExpr — target label
  ##   cRead:     readVars — variables to read into
  ##
  ## Genera Note: A command inspector would show the command kind,
  ## arguments, and for compound commands (IF, FOR), a tree of
  ## nested commands.
  Cmd* = ref object
    case kind*: CmdKind
    of cSet:
      setItems*: seq[SetItem]
    of cWrite:
      writeArgs*: seq[WriteArg]
    of cIf:
      ifCond*: Expr
      ifBody*: Line
    of cElse:
      elseBody*: Line
    of cFor:
      forSpec*: ForSpec
      forBody*: Line
    of cQuit:
      quitVal*: Expr
    of cKill:
      killRefs*: seq[Expr]
    of cKillExcept:
      killKeep*: seq[Expr]
    of cNew:
      newNames*: seq[string]
    of cHang:
      hangExpr*: Expr
    of cLock:
      lockRefs*: seq[Expr]
    of cMerge:
      mergePairs*: seq[(string, string)]
    of cXecute:
      xecExpr*: Expr
    of cDo:
      doArgs*: seq[Expr]
    of cDoInline:
      doInlineBody*: Line
    of cGoto:
      gotoExpr*: Expr
    of cBreak:
      discard
    of cNoop:
      discard
    of cZwrite:
      zwriteExpr*: Expr
    of cZkill:
      zkillExpr*: Expr
    of cOpen:
      openDevice*: Expr
      openParams*: Expr
    of cUse:
      useDevice*: Expr
    of cClose:
      closeDevice*: Expr
    of cRead:
      readVars*: seq[Expr]
    of cZhalt:
      zhaltCode*: Expr
    of cZmessage:
      zmessageExpr*: Expr
    of cZsave:
      zsaveExpr*: Expr
    of cZsystem:
      zsystemExpr*: Expr
    of cZtrap:
      ztrapExpr*: Expr
    of cZbreak:
      zbreakExpr*: Expr
    of cZgoto:
      zgotoExpr*: Expr
    of cZprint:
      zprintExpr*: Expr
    of cZquit:
      zquitExpr*: Expr
    of cZload:
      zloadExpr*: Expr
    of cZstep:
      zstepExpr*: Expr
    of cZcontinue:
      discard
    of cZremove:
      zremoveExpr*: Expr
