# ==============================================================================
# ANNOTATED SOURCE: pattern.nim — M/MUMPS Pattern Match Operator (?)
# ==============================================================================
#
# This file implements the M pattern match operator (?), one of M's most
# distinctive features. Pattern matching in M is NOT regex — it's a
# simple, positional, count-based system dating back to 1977.
#
# ANSI/MDC X11.1-1995 Standard References:
#   Section 7.5: Pattern Match Operator
#     syntax: expr ? pattern
#     pattern = patternatom | pattern patternatom
#     patternatom = count [.] code
#     count = integer (default 1)
#     code = A | N | E | U | L | P | C | H
#
#   Pattern Codes:
#     A — Alphabetic (A-Z, a-z)
#     N — Numeric (0-9)
#     E — Any character (the "everything" code)
#     U — Uppercase alphabetic (A-Z)
#     L — Lowercase alphabetic (a-z)
#     P — Punctuation (implementation-defined set)
#     C — Control characters (implementation-defined)
#     H — Hexadecimal digit (0-9, A-F, a-f)
#
#   The dot (.) means "or more" — e.g., 2.4A means 2 to 4 alphabetic,
#   while 2.A means 2 or more alphabetic. A bare dot (no count before)
#   means 1 or more (count defaults to 1).
#
# Design Decisions:
#   - Pattern matching is eager: it consumes as many matching characters
#     as possible before moving to the next atom. This is NOT backtracking.
#   - The set of punctuation characters is implementation-defined in the
#     standard. We use a reasonable ASCII set.
#   - Control character detection is not implemented (returns false) —
#     this is a pragmatic simplification for a text-processing language.
#   - Pattern atoms are stored in the AST as (count, code, orMore) triples,
#     not as strings. This allows efficient runtime matching.
#
# Genera-Style Introspection Notes:
#   - A pattern trace would show each atom being matched against the
#     string position, with consumed/matched/rejected status
#   - A Genera inspector would display the pattern as structured data:
#     "3U.2N" → [(3,'U',false), (2,'N',true)]
#   - Pattern debugging is notoriously hard in M; a visual debugger
#     would show the string with position markers and atom boundaries
#   - Static analysis: warn if a pattern can never match (e.g., 0A)
#   - Dynamic trace: log each atom match attempt with character position
#
# Cross-References:
#   - Used by: runtime.nim (eval for ePattern nodes)
#   - AST nodes: PatternAtom defined in ast.nim
#   - Generated by: parser.nim (parsePatternAtoms)
#   - Consumed by: runtime.nim (matchPattern called from eval)
#
# ==============================================================================

import std/strutils

import ast

## punctSet — The Implementation-Defined Punctuation Set
##
## ANSI/ISO Section 7.5 says P matches "punctuation characters" but
## leaves the exact set implementation-defined. We use the printable
## ASCII punctuation characters (excluding space, which is typically
## not considered punctuation in M implementations).
##
## Genera Note: A configurable punctuation set would allow the user
## to define what P means for their application. This is a common
## extension point in commercial M implementations.
const punctSet = {'!', '"', '#', '$', '%', '&', '\'', '(', ')', '*', '+', ',', '-',
  '.', '/', ':', ';', '<', '=', '>', '?', '@', '[', '\\', ']', '^', '_', '`',
  '{', '|', '}', '~'}

## matchesCode — Test a Single Character Against a Pattern Code
##
## ANSI/ISO Section 7.5.1: The pattern codes A, N, E, U, L, P, C, H
## each match a specific character class.
##
## Design Decision: We use set membership tests for O(1) matching.
## The code is case-insensitive (both 'A' and 'a' match code 'A').
## This matches the standard's specification that pattern codes are
## case-insensitive.
##
## Note on 'E': In M, E matches "any character" — it's the wildcard.
## It's commonly used in patterns like "1.E" meaning "one or more of
## anything" (i.e., non-empty string).
##
## Note on 'H': Hex digit matching is useful for validating hex strings.
## Note on 'C': Control characters are not well-defined for modern
## Unicode-aware systems; we return false for all printable chars.
##
## Genera Note: A pattern debugger would highlight which character
## matched which code, showing the match decision tree.
proc matchesCode*(c: char, code: char): bool =
  case code.toUpperAscii
  of 'A': c in {'A'..'Z', 'a'..'z'}
  of 'N': c in {'0'..'9'}
  of 'E': true
  of 'U': c in {'A'..'Z'}
  of 'L': c in {'a'..'z'}
  of 'P': c in punctSet
  of 'H': c in {'0'..'9', 'A'..'F', 'a'..'f'}
  else: false

## matchPattern — Match a String Against a Sequence of Pattern Atoms
##
## ANSI/ISO Section 7.5: "The pattern match operator evaluates its
## right operand as a pattern. The result is true if the left operand
## matches the pattern."
##
## Algorithm (greedy, non-backtracking):
##   1. For each atom in sequence:
##      a. Consume characters while they match the atom's code
##      b. If consumed < min count → FAIL
##      c. If not-orMore and consumed > min count → FAIL
##   2. All atoms matched AND all characters consumed → SUCCESS
##
## This is NOT regex. M patterns are positional and count-based:
##   "ABC"?1U1U1U   → true  (three uppercase letters)
##   "ABC"?3U       → true  (exactly three uppercase)
##   "ABC"?2U       → false (not exactly two)
##   "ABC"?2.U      → true  (two or more uppercase, consumed all 3)
##   "ABC"?2.4U     → true  (2-4 uppercase, consumed 3)
##   "ABC"?4U       → false (not enough characters)
##   "ABc"?3U       → false ('c' is not uppercase)
##   "ABc"?2U1L     → true  (two uppercase then one lowercase)
##
## Design Decision: The greedy algorithm means "2.4N" will consume
## as many digits as possible (up to 4). If you need "exactly 2 or
## 3", you must use "2N!3N" (logical OR of patterns) — but M doesn't
## have pattern OR, so you'd use "2.3N" which is 2-to-3.
##
## The final check `idx == s.len` ensures the entire string is consumed.
## If atoms remain after the string is exhausted, they fail (unless
## count is 0, which is unusual but valid).
##
## Genera Note: A step-through debugger would show:
##   String: "ABC"
##   Atom 1: 3U → consuming 'A' (match), 'B' (match), 'C' (match) → 3 matched
##   Remaining: "" (empty)
##   Result: true
##
## Cross-References:
##   - Called from: runtime.nim (eval, case ePattern)
##   - Input: atoms generated by parser.nim (parsePatternAtoms)
##   - AST type: PatternAtom from ast.nim
proc matchPattern*(s: string, atoms: seq[PatternAtom]): bool =
  var idx = 0
  for atom in atoms:
    let min = atom.count
    var matched = 0
    # For orMore atoms, consume greedily; for exact atoms, consume exactly min
    if atom.orMore:
      # Greedy: consume as many as possible
      while idx < s.len and matchesCode(s[idx], atom.code):
        inc idx
        inc matched
      if matched < min:
        return false
    else:
      # Exact: consume exactly min characters
      while matched < min and idx < s.len and matchesCode(s[idx], atom.code):
        inc idx
        inc matched
      if matched < min:
        return false
  idx == s.len

## atomToString — Render a Pattern Atom Back to M Source
##
## Utility for debugging, tracing, and $QUERY-like operations.
## Not used in normal execution but invaluable for introspection.
##
## Example: PatternAtom(count=3, code='U', orMore=false) → "3U"
##          PatternAtom(count=2, code='N', orMore=true)  → "2.N"
##
## Genera Note: This is exactly what a Genera describe function would
## call to display pattern atoms in human-readable form.
proc atomToString*(a: PatternAtom): string =
  var s = $a.count
  if a.orMore:
    s.add '.'
  s.add a.code
  s
